function compute_ws(k_input, TT)
    load(strcat(interm_folder,'/RQWfile.mat'));
    Ws_for_each_k(NR_vec, NQ_vec, nq_set, R_sqrt_root, number_of_cells,...
        number_of_users, number_of_antennas, targetCell, k_input,...
        pilotSequenceLength, mu, phi, alpha_R, alpha_Q, Rb, TT, Pb,...
        interm_folder);
end